### ISSUE TITLE
Error fetching information when using !play

### ISSUE THREAD

**Issue by Valerokai** [MinnDevelopment/MinnBot#15]
When using !play command the error message "A JSONObject text must begin with '{' at 1 [character 2 line 1]" is shown. This error message first appeared when playing https://www.youtube.com/watch?v=5bfseWNmlds and the server is hosted on a computer running Linux Mint, with the latest version of the Oracle JRE installed.

**Comment by MinnDevelopment** [comment]
That is a bug from Youtube-dl, I can't fix it

**Comment by Blackyvk** [comment]
is it a bug from newer versions? witch version is compatible ?
